project_name: ddtags

builds:
- skip: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Version }}"

release:
  footer: |
    **Full Changelog**: https://github.com/webdestroya/ddtags/compare/{{ .PreviousTag }}...{{ .Tag }}

changelog:
  skip: true