name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.22']
    name: Go ${{ matrix.go }} tests
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          cache: false # because it's broken?
          go-version: ${{ matrix.go }}

      - run: go test -timeout 180s ./...